services:
  spotlight.en:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.en
    volumes:
       - spotlight-models:/opt/spotlight/models
    ports:
       - 8601:80  
    command: /bin/spotlight.sh en
   
volumes:
  spotlight-models:
    external: true
